spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: DEPARTMENT-SERVICE
        uri: http://localhost:8080
#        uri: lb://DEPARTMENT-SERVICE
        predicates:
          - Path=/api/departments/**
      - id: EMPLOYEE-SERVICE
#        uri: lb://EMPLOYEE-SERVICE
        uri: http://localhost:8081
        predicates:
          - Path=/api/employees/**

server:
  port: 9191

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"


#  tracing:
#    sampling:
#      probability: 1
#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway: DEBUG

