spring:
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
#spring.datasource.url=jdbc:mysql://localhost:3306/department_db
#spring.datasource.username=root
#spring.datasource.password=India@123

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update


#eureka.client.register-with-eureka=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0