spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:mysql://localhost:3306/organization_db
    username: root
    password: India@123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8082
