server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nkolte/config-files-ms
          clone-on-start: true
          default-label: main
#          ignore-local-ssh-settings: true  # Uses default ~/.ssh/id_ed25519
#          private-key: |
#            -----BEGIN OPENSSH PRIVATE KEY-----
#
#            -----END OPENSSH PRIVATE KEY-----
#          host-key:
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
